testInputs:
	g++ avt440driver.cpp testInputs.cpp -o testInputs
mainLoopAvt440driver:
	g++ avt440driver.cpp mainLoopAvt440driver.cpp -o mainLoopAvt440driver
testAVT440driver:
	g++ avt440driver.cpp testAVT440driver.cpp -o testAVT440driver
testControll:
	g++ avt440driver.cpp testControll.cpp -o testControll
.PHONY: clean
clean:
	-rm testAVT440driver
	-rm mainLoopAvt440driver
	-rm testInputs
	-rm testControll
